version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    container_name: tcc-db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - tcc-postgres-data:/var/lib/postgresql/data
    networks:
      - tcc-network
    logging:
      driver: json-file
      options:
        max-size: 100m
volumes:
  tcc-postgres-data:
      name: tcc-postgres
networks:
  tcc-network:
    name: tcc-network