from .aluno_repository import AlunoRepository
from .professor_repository import ProfessorRepository
from .auth_repository import AuthRepository
from .solicitacao_repository import SolicitacaoRepository
